export enum SettingsVarsEnum {
  //STRIPE
  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',

  //VIMEO
  VIMEO_CLIENT_ID = 'VIMEO_CLIENT_ID',
  VIMEO_CLIENT_SECRET = 'VIMEO_CLIENT_SECRET',
  VIMEO_ACCESS_TOKEN = 'VIMEO_ACCESS_TOKEN',

  //MINIO
  MINIO_PORT = 'MINIO_PORT',
  MINIO_ENDPOINT = 'MINIO_ENDPOINT',
  MINIO_ACCESS_KEY = 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY = 'MINIO_SECRET_KEY',
  MINIO_BUCKET = 'MINIO_BUCKET',

  //Environments of App Store Connect
  APPLE_PUBLISHED_ID = 'APPLE_PUBLISHED_ID',
  APPLE_YOUR_API_KEY = 'APPLE_YOUR_API_KEY',
  APPLE_YOUR_ISSUER_ID = 'APPLE_YOUR_ISSUER_ID',
  APPLE_PRIVATE_KEY = 'APPLE_PRIVATE_KEY',
}
